package net.fabricmc.colorfulazaleas;

import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.fabricmc.fabric.api.particle.v1.FabricParticleTypes;
import net.minecraft.core.Registry;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.Material;
import net.minecraft.world.level.material.MaterialColor;
import org.intellij.lang.annotations.Identifier;

public class AzaleaBlocks {
    //Registration of the custom creative Tab
    public static final CreativeModeTab COLORFUL_AZALEAS = FabricItemGroupBuilder.create(new ResourceLocation(ColorfulAzaleas.MODID,"path")).icon(() -> new ItemStack(AzaleaBlocks.ORANGE_AZALEA_SAPLING)).build();

    //For simplicity, I split up the registry into a definition of blocks and their properties here
    //leaves
    public static final Block ORANGE_BLOOMING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES).requiresTool());
    public static final Block ORANGE_FLOWERING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block ORANGE_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block ORANGE_AZALEA_SAPLING = new OrangeAzaleaBlock(FabricBlockSettings.copyOf(Blocks.AZALEA).nonOpaque());
    public static final Block ORANGE_DROOPING_AZALEA_LEAVES = new DroopingLeavesBlock(FabricBlockSettings.of(Material.LEAVES).noCollision().sounds(SoundType.CAVE_VINES));
    public static final BlockItem ORANGE_BLOOMING_AZALEA_LEAVES_ITEM = new BlockItem(ORANGE_BLOOMING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem ORANGE_FLOWERING_AZALEA_LEAVES_ITEM = new BlockItem(ORANGE_FLOWERING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem ORANGE_AZALEA_LEAVES_ITEM = new BlockItem(ORANGE_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem ORANGE_AZALEA_SAPLING_ITEM = new BlockItem(ORANGE_AZALEA_SAPLING, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem ORANGE_DROOPING_AZALEA_LEAVES_ITEM = new BlockItem(ORANGE_DROOPING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BLUE_BLOOMING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block BLUE_FLOWERING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block BLUE_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block BLUE_AZALEA_SAPLING = new BlueAzaleaBlock(FabricBlockSettings.copyOf(Blocks.AZALEA).nonOpaque());
    public static final Block BLUE_DROOPING_AZALEA_LEAVES = new DroopingLeavesBlock(FabricBlockSettings.of(Material.LEAVES).noCollision().sounds(SoundType.CAVE_VINES));
    public static final BlockItem BLUE_BLOOMING_AZALEA_LEAVES_ITEM = new BlockItem(BLUE_BLOOMING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem BLUE_FLOWERING_AZALEA_LEAVES_ITEM = new BlockItem(BLUE_FLOWERING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem BLUE_AZALEA_LEAVES_ITEM = new BlockItem(BLUE_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem BLUE_AZALEA_SAPLING_ITEM = new BlockItem(BLUE_AZALEA_SAPLING, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem BLUE_DROOPING_AZALEA_LEAVES_ITEM = new BlockItem(BLUE_DROOPING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block RED_BLOOMING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block RED_FLOWERING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block RED_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block RED_AZALEA_SAPLING = new RedAzaleaBlock(FabricBlockSettings.copyOf(Blocks.AZALEA).nonOpaque());
    public static final Block RED_DROOPING_AZALEA_LEAVES = new DroopingLeavesBlock(FabricBlockSettings.of(Material.LEAVES).noCollision().sounds(SoundType.CAVE_VINES));
    public static final BlockItem RED_BLOOMING_AZALEA_LEAVES_ITEM = new BlockItem(RED_BLOOMING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem RED_FLOWERING_AZALEA_LEAVES_ITEM = new BlockItem(RED_FLOWERING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem RED_AZALEA_LEAVES_ITEM = new BlockItem(RED_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem RED_AZALEA_SAPLING_ITEM = new BlockItem(RED_AZALEA_SAPLING, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem RED_DROOPING_AZALEA_LEAVES_ITEM = new BlockItem(RED_DROOPING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block PURPLE_BLOOMING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block PURPLE_FLOWERING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block PURPLE_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block PURPLE_AZALEA_SAPLING = new PurpleAzaleaBlock(FabricBlockSettings.copyOf(Blocks.AZALEA).nonOpaque());
    public static final Block PURPLE_DROOPING_AZALEA_LEAVES = new DroopingLeavesBlock(FabricBlockSettings.of(Material.LEAVES).noCollision().sounds(SoundType.CAVE_VINES));
    public static final BlockItem PURPLE_BLOOMING_AZALEA_LEAVES_ITEM = new BlockItem(PURPLE_BLOOMING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem PURPLE_FLOWERING_AZALEA_LEAVES_ITEM = new BlockItem(PURPLE_FLOWERING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem PURPLE_AZALEA_LEAVES_ITEM = new BlockItem(PURPLE_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem PURPLE_AZALEA_SAPLING_ITEM = new BlockItem(PURPLE_AZALEA_SAPLING, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem PURPLE_DROOPING_AZALEA_LEAVES_ITEM = new BlockItem(PURPLE_DROOPING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block PINK_BLOOMING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block PINK_FLOWERING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block PINK_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block PINK_AZALEA_SAPLING = new PinkAzaleaBlock(FabricBlockSettings.copyOf(Blocks.AZALEA).nonOpaque());
    public static final Block PINK_DROOPING_AZALEA_LEAVES = new DroopingLeavesBlock(FabricBlockSettings.of(Material.LEAVES).noCollision().sounds(SoundType.CAVE_VINES));
    public static final BlockItem PINK_BLOOMING_AZALEA_LEAVES_ITEM = new BlockItem(PINK_BLOOMING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem PINK_FLOWERING_AZALEA_LEAVES_ITEM = new BlockItem(PINK_FLOWERING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem PINK_AZALEA_LEAVES_ITEM = new BlockItem(PINK_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem PINK_AZALEA_SAPLING_ITEM = new BlockItem(PINK_AZALEA_SAPLING, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem PINK_DROOPING_AZALEA_LEAVES_ITEM = new BlockItem(PINK_DROOPING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WHITE_BLOOMING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block WHITE_FLOWERING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block WHITE_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block WHITE_AZALEA_SAPLING = new WhiteAzaleaBlock(FabricBlockSettings.copyOf(Blocks.AZALEA).nonOpaque());
    public static final Block WHITE_DROOPING_AZALEA_LEAVES = new DroopingLeavesBlock(FabricBlockSettings.of(Material.LEAVES).noCollision().sounds(SoundType.CAVE_VINES));
    public static final BlockItem WHITE_BLOOMING_AZALEA_LEAVES_ITEM = new BlockItem(WHITE_BLOOMING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem WHITE_FLOWERING_AZALEA_LEAVES_ITEM = new BlockItem(WHITE_FLOWERING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem WHITE_AZALEA_LEAVES_ITEM = new BlockItem(WHITE_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem WHITE_AZALEA_SAPLING_ITEM = new BlockItem(WHITE_AZALEA_SAPLING, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem WHITE_DROOPING_AZALEA_LEAVES_ITEM = new BlockItem(WHITE_DROOPING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block YELLOW_BLOOMING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block YELLOW_FLOWERING_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block YELLOW_AZALEA_LEAVES = new LeavesBlock(FabricBlockSettings.copyOf(Blocks.AZALEA_LEAVES));
    public static final Block YELLOW_AZALEA_SAPLING = new YellowAzaleaBlock(FabricBlockSettings.copyOf(Blocks.AZALEA).nonOpaque());
    public static final Block YELLOW_DROOPING_AZALEA_LEAVES = new DroopingLeavesBlock(FabricBlockSettings.of(Material.LEAVES).noCollision().sounds(SoundType.CAVE_VINES));
    public static final BlockItem YELLOW_BLOOMING_AZALEA_LEAVES_ITEM = new BlockItem(YELLOW_BLOOMING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem YELLOW_FLOWERING_AZALEA_LEAVES_ITEM = new BlockItem(YELLOW_FLOWERING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem YELLOW_AZALEA_LEAVES_ITEM = new BlockItem(YELLOW_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem YELLOW_AZALEA_SAPLING_ITEM = new BlockItem(YELLOW_AZALEA_SAPLING, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final BlockItem YELLOW_DROOPING_AZALEA_LEAVES_ITEM = new BlockItem(YELLOW_DROOPING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block DROOPING_AZALEA_LEAVES = new DroopingLeavesBlock(FabricBlockSettings.of(Material.LEAVES).noCollision().sounds(SoundType.CAVE_VINES));
    public static final BlockItem DROOPING_AZALEA_LEAVES_ITEM = new BlockItem(DROOPING_AZALEA_LEAVES, new Item.Properties().tab(COLORFUL_AZALEAS));

    //woods
    public static final Block AZULE_AZALEA_PLANKS = new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS));
    public static final BlockItem AZULE_AZALEA_PLANKS_ITEM = new BlockItem(AZULE_AZALEA_PLANKS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG));
    public static final BlockItem AZULE_AZALEA_LOG_ITEM = new BlockItem(AZULE_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_AZULE_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_LOG));
    public static final BlockItem STRIPPED_AZULE_AZALEA_LOG_ITEM = new BlockItem(STRIPPED_AZULE_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_PLANKS = new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS));
    public static final BlockItem BRIGHT_AZALEA_PLANKS_ITEM = new BlockItem(BRIGHT_AZALEA_PLANKS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG));
    public static final BlockItem BRIGHT_AZALEA_LOG_ITEM = new BlockItem(BRIGHT_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_BRIGHT_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_LOG));
    public static final BlockItem STRIPPED_BRIGHT_AZALEA_LOG_ITEM = new BlockItem(STRIPPED_BRIGHT_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_PLANKS = new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS));
    public static final BlockItem ROZE_AZALEA_PLANKS_ITEM = new BlockItem(ROZE_AZALEA_PLANKS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG));
    public static final BlockItem ROZE_AZALEA_LOG_ITEM = new BlockItem(ROZE_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_ROZE_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_LOG));
    public static final BlockItem STRIPPED_ROZE_AZALEA_LOG_ITEM = new BlockItem(STRIPPED_ROZE_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_PLANKS = new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS));
    public static final BlockItem TECAL_AZALEA_PLANKS_ITEM = new BlockItem(TECAL_AZALEA_PLANKS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG));
    public static final BlockItem TECAL_AZALEA_LOG_ITEM = new BlockItem(TECAL_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_TECAL_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_LOG));
    public static final BlockItem STRIPPED_TECAL_AZALEA_LOG_ITEM = new BlockItem(STRIPPED_TECAL_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_PLANKS = new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS));
    public static final BlockItem TITANIUM_AZALEA_PLANKS_ITEM = new BlockItem(TITANIUM_AZALEA_PLANKS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG));
    public static final BlockItem TITANIUM_AZALEA_LOG_ITEM = new BlockItem(TITANIUM_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_TITANIUM_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_LOG));
    public static final BlockItem STRIPPED_TITANIUM_AZALEA_LOG_ITEM = new BlockItem(STRIPPED_TITANIUM_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_PLANKS = new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS));
    public static final BlockItem WALNUT_AZALEA_PLANKS_ITEM = new BlockItem(WALNUT_AZALEA_PLANKS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG));
    public static final BlockItem WALNUT_AZALEA_LOG_ITEM = new BlockItem(WALNUT_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_WALNUT_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_LOG));
    public static final BlockItem STRIPPED_WALNUT_AZALEA_LOG_ITEM = new BlockItem(STRIPPED_WALNUT_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_PLANKS = new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS));
    public static final BlockItem FISS_AZALEA_PLANKS_ITEM = new BlockItem(FISS_AZALEA_PLANKS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG));
    public static final BlockItem FISS_AZALEA_LOG_ITEM = new BlockItem(FISS_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_FISS_AZALEA_LOG = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_LOG));
    public static final BlockItem STRIPPED_FISS_AZALEA_LOG_ITEM = new BlockItem(STRIPPED_FISS_AZALEA_LOG, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_WOOD));
    public static final BlockItem AZULE_AZALEA_WOOD_ITEM = new BlockItem(AZULE_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_AZULE_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_WOOD));
    public static final BlockItem STRIPPED_AZULE_AZALEA_WOOD_ITEM = new BlockItem(STRIPPED_AZULE_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_WOOD));
    public static final BlockItem BRIGHT_AZALEA_WOOD_ITEM = new BlockItem(BRIGHT_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_BRIGHT_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_WOOD));
    public static final BlockItem STRIPPED_BRIGHT_AZALEA_WOOD_ITEM = new BlockItem(STRIPPED_BRIGHT_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_WOOD));
    public static final BlockItem ROZE_AZALEA_WOOD_ITEM = new BlockItem(ROZE_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_ROZE_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_WOOD));
    public static final BlockItem STRIPPED_ROZE_AZALEA_WOOD_ITEM = new BlockItem(STRIPPED_ROZE_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_WOOD));
    public static final BlockItem TECAL_AZALEA_WOOD_ITEM = new BlockItem(TECAL_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_TECAL_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_WOOD));
    public static final BlockItem STRIPPED_TECAL_AZALEA_WOOD_ITEM = new BlockItem(STRIPPED_TECAL_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_WOOD));
    public static final BlockItem TITANIUM_AZALEA_WOOD_ITEM = new BlockItem(TITANIUM_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_TITANIUM_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_WOOD));
    public static final BlockItem STRIPPED_TITANIUM_AZALEA_WOOD_ITEM = new BlockItem(STRIPPED_TITANIUM_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_WOOD));
    public static final BlockItem WALNUT_AZALEA_WOOD_ITEM = new BlockItem(WALNUT_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_WALNUT_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_WOOD));
    public static final BlockItem STRIPPED_WALNUT_AZALEA_WOOD_ITEM = new BlockItem(STRIPPED_WALNUT_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_WOOD));
    public static final BlockItem FISS_AZALEA_WOOD_ITEM = new BlockItem(FISS_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block STRIPPED_FISS_AZALEA_WOOD = new RotatedPillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_WOOD));
    public static final BlockItem STRIPPED_FISS_AZALEA_WOOD_ITEM = new BlockItem(STRIPPED_FISS_AZALEA_WOOD, new Item.Properties().tab(COLORFUL_AZALEAS));

    //wood craftings
    public static final Block FISS_AZALEA_STAIRS = new StairBlock(FISS_AZALEA_PLANKS.defaultBlockState(), BlockBehaviour.Properties.copy(FISS_AZALEA_PLANKS));
    public static final BlockItem FISS_AZALEA_STAIRS_ITEM = new BlockItem(FISS_AZALEA_STAIRS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_STAIRS = new StairBlock(TITANIUM_AZALEA_PLANKS.defaultBlockState(), BlockBehaviour.Properties.copy(TITANIUM_AZALEA_PLANKS));
    public static final BlockItem TITANIUM_AZALEA_STAIRS_ITEM = new BlockItem(TITANIUM_AZALEA_STAIRS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_STAIRS = new StairBlock(WALNUT_AZALEA_PLANKS.defaultBlockState(), BlockBehaviour.Properties.copy(WALNUT_AZALEA_PLANKS));
    public static final BlockItem WALNUT_AZALEA_STAIRS_ITEM = new BlockItem(WALNUT_AZALEA_STAIRS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_STAIRS = new StairBlock(ROZE_AZALEA_PLANKS.defaultBlockState(), BlockBehaviour.Properties.copy(ROZE_AZALEA_PLANKS));
    public static final BlockItem ROZE_AZALEA_STAIRS_ITEM = new BlockItem(ROZE_AZALEA_STAIRS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_STAIRS = new StairBlock(TECAL_AZALEA_PLANKS.defaultBlockState(), BlockBehaviour.Properties.copy(TECAL_AZALEA_PLANKS));
    public static final BlockItem TECAL_AZALEA_STAIRS_ITEM = new BlockItem(TECAL_AZALEA_STAIRS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_STAIRS = new StairBlock(BRIGHT_AZALEA_PLANKS.defaultBlockState(), BlockBehaviour.Properties.copy(BRIGHT_AZALEA_PLANKS));
    public static final BlockItem BRIGHT_AZALEA_STAIRS_ITEM = new BlockItem(BRIGHT_AZALEA_STAIRS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_STAIRS = new StairBlock(AZULE_AZALEA_PLANKS.defaultBlockState(), BlockBehaviour.Properties.copy(AZULE_AZALEA_PLANKS));
    public static final BlockItem AZULE_AZALEA_STAIRS_ITEM = new BlockItem(AZULE_AZALEA_STAIRS, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB));
    public static final BlockItem FISS_AZALEA_SLAB_ITEM = new BlockItem(FISS_AZALEA_SLAB, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB));
    public static final BlockItem TITANIUM_AZALEA_SLAB_ITEM = new BlockItem(TITANIUM_AZALEA_SLAB, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB));
    public static final BlockItem WALNUT_AZALEA_SLAB_ITEM = new BlockItem(WALNUT_AZALEA_SLAB, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB));
    public static final BlockItem ROZE_AZALEA_SLAB_ITEM = new BlockItem(ROZE_AZALEA_SLAB, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB));
    public static final BlockItem TECAL_AZALEA_SLAB_ITEM = new BlockItem(TECAL_AZALEA_SLAB, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB));
    public static final BlockItem BRIGHT_AZALEA_SLAB_ITEM = new BlockItem(BRIGHT_AZALEA_SLAB, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB));
    public static final BlockItem AZULE_AZALEA_SLAB_ITEM = new BlockItem(AZULE_AZALEA_SLAB, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_TRAPDOOR = new TrapDoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_TRAPDOOR));
    public static final BlockItem FISS_AZALEA_TRAPDOOR_ITEM = new BlockItem(FISS_AZALEA_TRAPDOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_TRAPDOOR = new TrapDoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_TRAPDOOR));
    public static final BlockItem TITANIUM_AZALEA_TRAPDOOR_ITEM = new BlockItem(TITANIUM_AZALEA_TRAPDOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_TRAPDOOR = new TrapDoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_TRAPDOOR));
    public static final BlockItem WALNUT_AZALEA_TRAPDOOR_ITEM = new BlockItem(WALNUT_AZALEA_TRAPDOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_TRAPDOOR = new TrapDoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_TRAPDOOR));
    public static final BlockItem ROZE_AZALEA_TRAPDOOR_ITEM = new BlockItem(ROZE_AZALEA_TRAPDOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_TRAPDOOR = new TrapDoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_TRAPDOOR));
    public static final BlockItem TECAL_AZALEA_TRAPDOOR_ITEM = new BlockItem(TECAL_AZALEA_TRAPDOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_TRAPDOOR = new TrapDoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_TRAPDOOR));
    public static final BlockItem BRIGHT_AZALEA_TRAPDOOR_ITEM = new BlockItem(BRIGHT_AZALEA_TRAPDOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_TRAPDOOR = new TrapDoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_TRAPDOOR));
    public static final BlockItem AZULE_AZALEA_TRAPDOOR_ITEM = new BlockItem(AZULE_AZALEA_TRAPDOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_DOOR = new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR));
    public static final BlockItem FISS_AZALEA_DOOR_ITEM = new BlockItem(FISS_AZALEA_DOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_DOOR = new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR));
    public static final BlockItem TITANIUM_AZALEA_DOOR_ITEM = new BlockItem(TITANIUM_AZALEA_DOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_DOOR = new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR));
    public static final BlockItem WALNUT_AZALEA_DOOR_ITEM = new BlockItem(WALNUT_AZALEA_DOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_DOOR = new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR));
    public static final BlockItem ROZE_AZALEA_DOOR_ITEM = new BlockItem(ROZE_AZALEA_DOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_DOOR = new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR));
    public static final BlockItem TECAL_AZALEA_DOOR_ITEM = new BlockItem(TECAL_AZALEA_DOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_DOOR = new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR));
    public static final BlockItem BRIGHT_AZALEA_DOOR_ITEM = new BlockItem(BRIGHT_AZALEA_DOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_DOOR = new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR));
    public static final BlockItem AZULE_AZALEA_DOOR_ITEM = new BlockItem(AZULE_AZALEA_DOOR, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_FENCE_GATE = new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE_GATE));
    public static final BlockItem FISS_AZALEA_FENCE_GATE_ITEM = new BlockItem(FISS_AZALEA_FENCE_GATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_FENCE_GATE = new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE_GATE));
    public static final BlockItem TITANIUM_AZALEA_FENCE_GATE_ITEM = new BlockItem(TITANIUM_AZALEA_FENCE_GATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_FENCE_GATE = new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE_GATE));
    public static final BlockItem WALNUT_AZALEA_FENCE_GATE_ITEM = new BlockItem(WALNUT_AZALEA_FENCE_GATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_FENCE_GATE = new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE_GATE));
    public static final BlockItem ROZE_AZALEA_FENCE_GATE_ITEM = new BlockItem(ROZE_AZALEA_FENCE_GATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_FENCE_GATE = new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE_GATE));
    public static final BlockItem TECAL_AZALEA_FENCE_GATE_ITEM = new BlockItem(TECAL_AZALEA_FENCE_GATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_FENCE_GATE = new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE_GATE));
    public static final BlockItem BRIGHT_AZALEA_FENCE_GATE_ITEM = new BlockItem(BRIGHT_AZALEA_FENCE_GATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_FENCE_GATE = new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE_GATE));
    public static final BlockItem AZULE_AZALEA_FENCE_GATE_ITEM = new BlockItem(AZULE_AZALEA_FENCE_GATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_BUTTON = new WoodButtonBlock(FabricBlockSettings.copyOf(Blocks.OAK_BUTTON));
    public static final BlockItem FISS_AZALEA_BUTTON_ITEM = new BlockItem(FISS_AZALEA_BUTTON, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_BUTTON = new WoodButtonBlock(FabricBlockSettings.copyOf(Blocks.OAK_BUTTON));
    public static final BlockItem TITANIUM_AZALEA_BUTTON_ITEM = new BlockItem(TITANIUM_AZALEA_BUTTON, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_BUTTON = new WoodButtonBlock(FabricBlockSettings.copyOf(Blocks.OAK_BUTTON)) {};
    public static final BlockItem WALNUT_AZALEA_BUTTON_ITEM = new BlockItem(WALNUT_AZALEA_BUTTON, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_BUTTON = new WoodButtonBlock(FabricBlockSettings.copyOf(Blocks.OAK_BUTTON));
    public static final BlockItem ROZE_AZALEA_BUTTON_ITEM = new BlockItem(ROZE_AZALEA_BUTTON, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_BUTTON = new WoodButtonBlock(FabricBlockSettings.copyOf(Blocks.OAK_BUTTON));
    public static final BlockItem TECAL_AZALEA_BUTTON_ITEM = new BlockItem(TECAL_AZALEA_BUTTON, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_BUTTON = new WoodButtonBlock(FabricBlockSettings.copyOf(Blocks.OAK_BUTTON));
    public static final BlockItem BRIGHT_AZALEA_BUTTON_ITEM = new BlockItem(BRIGHT_AZALEA_BUTTON, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_BUTTON = new WoodButtonBlock(FabricBlockSettings.copyOf(Blocks.OAK_BUTTON));
    public static final BlockItem AZULE_AZALEA_BUTTON_ITEM = new BlockItem(AZULE_AZALEA_BUTTON, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_PRESSURE_PLATE = new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, FabricBlockSettings.copyOf(Blocks.OAK_PRESSURE_PLATE));
    public static final BlockItem FISS_AZALEA_PRESSURE_PLATE_ITEM = new BlockItem(FISS_AZALEA_PRESSURE_PLATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_PRESSURE_PLATE = new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, FabricBlockSettings.copyOf(Blocks.OAK_PRESSURE_PLATE));
    public static final BlockItem TITANIUM_AZALEA_PRESSURE_PLATE_ITEM = new BlockItem(TITANIUM_AZALEA_PRESSURE_PLATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_PRESSURE_PLATE = new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, FabricBlockSettings.copyOf(Blocks.OAK_PRESSURE_PLATE));
    public static final BlockItem WALNUT_AZALEA_PRESSURE_PLATE_ITEM = new BlockItem(WALNUT_AZALEA_PRESSURE_PLATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_PRESSURE_PLATE = new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, FabricBlockSettings.copyOf(Blocks.OAK_PRESSURE_PLATE));
    public static final BlockItem ROZE_AZALEA_PRESSURE_PLATE_ITEM = new BlockItem(ROZE_AZALEA_PRESSURE_PLATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_PRESSURE_PLATE = new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, FabricBlockSettings.copyOf(Blocks.OAK_PRESSURE_PLATE));
    public static final BlockItem TECAL_AZALEA_PRESSURE_PLATE_ITEM = new BlockItem(TECAL_AZALEA_PRESSURE_PLATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_PRESSURE_PLATE = new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, FabricBlockSettings.copyOf(Blocks.OAK_PRESSURE_PLATE));
    public static final BlockItem BRIGHT_AZALEA_PRESSURE_PLATE_ITEM = new BlockItem(BRIGHT_AZALEA_PRESSURE_PLATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_PRESSURE_PLATE = new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, FabricBlockSettings.copyOf(Blocks.OAK_PRESSURE_PLATE));
    public static final BlockItem AZULE_AZALEA_PRESSURE_PLATE_ITEM = new BlockItem(AZULE_AZALEA_PRESSURE_PLATE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block FISS_AZALEA_FENCE = new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE)) {};
    public static final BlockItem FISS_AZALEA_FENCE_ITEM = new BlockItem(FISS_AZALEA_FENCE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TITANIUM_AZALEA_FENCE = new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE));
    public static final BlockItem TITANIUM_AZALEA_FENCE_ITEM = new BlockItem(TITANIUM_AZALEA_FENCE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block WALNUT_AZALEA_FENCE = new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE)) {};
    public static final BlockItem WALNUT_AZALEA_FENCE_ITEM = new BlockItem(WALNUT_AZALEA_FENCE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block ROZE_AZALEA_FENCE = new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE));
    public static final BlockItem ROZE_AZALEA_FENCE_ITEM = new BlockItem(ROZE_AZALEA_FENCE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block TECAL_AZALEA_FENCE = new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE));
    public static final BlockItem TECAL_AZALEA_FENCE_ITEM = new BlockItem(TECAL_AZALEA_FENCE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block BRIGHT_AZALEA_FENCE = new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE));
    public static final BlockItem BRIGHT_AZALEA_FENCE_ITEM = new BlockItem(BRIGHT_AZALEA_FENCE, new Item.Properties().tab(COLORFUL_AZALEAS));
    public static final Block AZULE_AZALEA_FENCE = new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE));
    public static final BlockItem AZULE_AZALEA_FENCE_ITEM = new BlockItem(AZULE_AZALEA_FENCE, new Item.Properties().tab(COLORFUL_AZALEAS));

    //Registry of all blocks and items into the game
    public static void registerBlock() {
        
        //Registry of Blocks
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"orange_blooming_azalea_leaves"), ORANGE_BLOOMING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"orange_flowering_azalea_leaves"), ORANGE_FLOWERING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"orange_azalea_leaves"), ORANGE_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "orange_azalea_sapling"), ORANGE_AZALEA_SAPLING);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "orange_drooping_azalea_leaves"), ORANGE_DROOPING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"red_blooming_azalea_leaves"), RED_BLOOMING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"red_flowering_azalea_leaves"), RED_FLOWERING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"red_azalea_leaves"), RED_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "red_azalea_sapling"), RED_AZALEA_SAPLING);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "red_drooping_azalea_leaves"), RED_DROOPING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"pink_blooming_azalea_leaves"), PINK_BLOOMING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"pink_flowering_azalea_leaves"), PINK_FLOWERING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"pink_azalea_leaves"), PINK_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "pink_azalea_sapling"), PINK_AZALEA_SAPLING);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "pink_drooping_azalea_leaves"), PINK_DROOPING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"purple_blooming_azalea_leaves"), PURPLE_BLOOMING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"purple_flowering_azalea_leaves"), PURPLE_FLOWERING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"purple_azalea_leaves"), PURPLE_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "purple_azalea_sapling"), PURPLE_AZALEA_SAPLING);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "purple_drooping_azalea_leaves"), PURPLE_DROOPING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"white_blooming_azalea_leaves"), WHITE_BLOOMING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"white_flowering_azalea_leaves"), WHITE_FLOWERING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"white_azalea_leaves"), WHITE_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "white_azalea_sapling"), WHITE_AZALEA_SAPLING);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "white_drooping_azalea_leaves"), WHITE_DROOPING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"yellow_blooming_azalea_leaves"), YELLOW_BLOOMING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"yellow_flowering_azalea_leaves"), YELLOW_FLOWERING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"yellow_azalea_leaves"), YELLOW_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "yellow_azalea_sapling"), YELLOW_AZALEA_SAPLING);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "yellow_drooping_azalea_leaves"), YELLOW_DROOPING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "drooping_azalea_leaves"), DROOPING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"blue_blooming_azalea_leaves"), BLUE_BLOOMING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"blue_flowering_azalea_leaves"), BLUE_FLOWERING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID,"blue_azalea_leaves"), BLUE_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "blue_azalea_sapling"), BLUE_AZALEA_SAPLING);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "blue_drooping_azalea_leaves"), BLUE_DROOPING_AZALEA_LEAVES);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_planks"), AZULE_AZALEA_PLANKS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_log"), AZULE_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_azule_azalea_log"), STRIPPED_AZULE_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_planks"), BRIGHT_AZALEA_PLANKS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_bright_azalea_log"), STRIPPED_BRIGHT_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_log"), BRIGHT_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_planks"), ROZE_AZALEA_PLANKS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_roze_azalea_log"), STRIPPED_ROZE_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_log"), ROZE_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_planks"), TECAL_AZALEA_PLANKS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_tecal_azalea_log"), STRIPPED_TECAL_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_log"), TECAL_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_planks"), TITANIUM_AZALEA_PLANKS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_titanium_azalea_log"), STRIPPED_TITANIUM_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_log"), TITANIUM_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_planks"), WALNUT_AZALEA_PLANKS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_planks"), FISS_AZALEA_PLANKS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_walnut_azalea_log"), STRIPPED_WALNUT_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_fiss_azalea_log"), STRIPPED_FISS_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_log"), WALNUT_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_log"), FISS_AZALEA_LOG);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_wood"), AZULE_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_azule_azalea_wood"), STRIPPED_AZULE_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_bright_azalea_wood"), STRIPPED_BRIGHT_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_wood"), BRIGHT_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_roze_azalea_wood"), STRIPPED_ROZE_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_wood"), ROZE_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_tecal_azalea_wood"), STRIPPED_TECAL_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_wood"), TECAL_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_titanium_azalea_wood"), STRIPPED_TITANIUM_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_wood"), TITANIUM_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_walnut_azalea_wood"), STRIPPED_WALNUT_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_fiss_azalea_wood"), STRIPPED_FISS_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_wood"), WALNUT_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_wood"), FISS_AZALEA_WOOD);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_fence"), FISS_AZALEA_FENCE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_fence"), TITANIUM_AZALEA_FENCE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_fence"), WALNUT_AZALEA_FENCE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_fence"), ROZE_AZALEA_FENCE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_fence"), BRIGHT_AZALEA_FENCE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_fence"), TECAL_AZALEA_FENCE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_fence"), AZULE_AZALEA_FENCE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_fence_gate"), FISS_AZALEA_FENCE_GATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_fence_gate"), TITANIUM_AZALEA_FENCE_GATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_fence_gate"), WALNUT_AZALEA_FENCE_GATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_fence_gate"), ROZE_AZALEA_FENCE_GATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_fence_gate"), BRIGHT_AZALEA_FENCE_GATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_fence_gate"), TECAL_AZALEA_FENCE_GATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_fence_gate"), AZULE_AZALEA_FENCE_GATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_trapdoor"), FISS_AZALEA_TRAPDOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_trapdoor"), TITANIUM_AZALEA_TRAPDOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_trapdoor"), WALNUT_AZALEA_TRAPDOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_trapdoor"), ROZE_AZALEA_TRAPDOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_trapdoor"), BRIGHT_AZALEA_TRAPDOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_trapdoor"), TECAL_AZALEA_TRAPDOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_trapdoor"), AZULE_AZALEA_TRAPDOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_door"), FISS_AZALEA_DOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_door"), TITANIUM_AZALEA_DOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_door"), WALNUT_AZALEA_DOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_door"), ROZE_AZALEA_DOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_door"), BRIGHT_AZALEA_DOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_door"), TECAL_AZALEA_DOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_door"), AZULE_AZALEA_DOOR);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_stairs"), FISS_AZALEA_STAIRS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_stairs"), TITANIUM_AZALEA_STAIRS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_stairs"), WALNUT_AZALEA_STAIRS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_stairs"), ROZE_AZALEA_STAIRS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_stairs"), BRIGHT_AZALEA_STAIRS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_stairs"), TECAL_AZALEA_STAIRS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_stairs"), AZULE_AZALEA_STAIRS);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_slab"), FISS_AZALEA_SLAB);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_slab"), TITANIUM_AZALEA_SLAB);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_slab"), WALNUT_AZALEA_SLAB);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_slab"), ROZE_AZALEA_SLAB);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_slab"), BRIGHT_AZALEA_SLAB);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_slab"), TECAL_AZALEA_SLAB);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_slab"), AZULE_AZALEA_SLAB);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_button"), FISS_AZALEA_BUTTON);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_button"), TITANIUM_AZALEA_BUTTON);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_button"), WALNUT_AZALEA_BUTTON);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_button"), ROZE_AZALEA_BUTTON);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_button"), BRIGHT_AZALEA_BUTTON);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_button"), TECAL_AZALEA_BUTTON);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_button"), AZULE_AZALEA_BUTTON);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_pressure_plate"), FISS_AZALEA_PRESSURE_PLATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_pressure_plate"), TITANIUM_AZALEA_PRESSURE_PLATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_pressure_plate"), WALNUT_AZALEA_PRESSURE_PLATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_pressure_plate"), ROZE_AZALEA_PRESSURE_PLATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_pressure_plate"), BRIGHT_AZALEA_PRESSURE_PLATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_pressure_plate"), TECAL_AZALEA_PRESSURE_PLATE);
        Registry.register(Registry.BLOCK, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_pressure_plate"), AZULE_AZALEA_PRESSURE_PLATE);

        //Registry of Items
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "orange_blooming_azalea_leaves"), ORANGE_BLOOMING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "red_blooming_azalea_leaves"), RED_BLOOMING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "blue_blooming_azalea_leaves"), BLUE_BLOOMING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "yellow_blooming_azalea_leaves"), YELLOW_BLOOMING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "pink_blooming_azalea_leaves"), PINK_BLOOMING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "purple_blooming_azalea_leaves"), PURPLE_BLOOMING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "white_blooming_azalea_leaves"), WHITE_BLOOMING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "orange_flowering_azalea_leaves"), ORANGE_FLOWERING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "red_flowering_azalea_leaves"), RED_FLOWERING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "blue_flowering_azalea_leaves"), BLUE_FLOWERING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "yellow_flowering_azalea_leaves"), YELLOW_FLOWERING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "pink_flowering_azalea_leaves"), PINK_FLOWERING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "purple_flowering_azalea_leaves"), PURPLE_FLOWERING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "white_flowering_azalea_leaves"), WHITE_FLOWERING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "orange_azalea_leaves"), ORANGE_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "red_azalea_leaves"), RED_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "blue_azalea_leaves"), BLUE_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "yellow_azalea_leaves"), YELLOW_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "pink_azalea_leaves"), PINK_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "purple_azalea_leaves"), PURPLE_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "white_azalea_leaves"), WHITE_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "orange_azalea_sapling"), ORANGE_AZALEA_SAPLING_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "red_azalea_sapling"), RED_AZALEA_SAPLING_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "blue_azalea_sapling"), BLUE_AZALEA_SAPLING_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "yellow_azalea_sapling"), YELLOW_AZALEA_SAPLING_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "pink_azalea_sapling"), PINK_AZALEA_SAPLING_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "purple_azalea_sapling"), PURPLE_AZALEA_SAPLING_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "white_azalea_sapling"), WHITE_AZALEA_SAPLING_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "orange_drooping_azalea_leaves"), ORANGE_DROOPING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "red_drooping_azalea_leaves"), RED_DROOPING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "blue_drooping_azalea_leaves"), BLUE_DROOPING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "yellow_drooping_azalea_leaves"), YELLOW_DROOPING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "drooping_azalea_leaves"), DROOPING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "pink_drooping_azalea_leaves"), PINK_DROOPING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "purple_drooping_azalea_leaves"), PURPLE_DROOPING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "white_drooping_azalea_leaves"), WHITE_DROOPING_AZALEA_LEAVES_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_planks"), WALNUT_AZALEA_PLANKS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_planks"), FISS_AZALEA_PLANKS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_planks"), TITANIUM_AZALEA_PLANKS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_planks"), TECAL_AZALEA_PLANKS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_planks"), ROZE_AZALEA_PLANKS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_planks"), BRIGHT_AZALEA_PLANKS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_planks"), AZULE_AZALEA_PLANKS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_walnut_azalea_log"), STRIPPED_WALNUT_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_fiss_azalea_log"), STRIPPED_FISS_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_titanium_azalea_log"), STRIPPED_TITANIUM_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_tecal_azalea_log"), STRIPPED_TECAL_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_roze_azalea_log"), STRIPPED_ROZE_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_bright_azalea_log"), STRIPPED_BRIGHT_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_azule_azalea_log"), STRIPPED_AZULE_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_log"), WALNUT_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_log"), FISS_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_log"), TITANIUM_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_log"), TECAL_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_log"), ROZE_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_log"), BRIGHT_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_log"), AZULE_AZALEA_LOG_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_walnut_azalea_wood"), STRIPPED_WALNUT_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_fiss_azalea_wood"), STRIPPED_FISS_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_titanium_azalea_wood"), STRIPPED_TITANIUM_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_tecal_azalea_wood"), STRIPPED_TECAL_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_roze_azalea_wood"), STRIPPED_ROZE_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_bright_azalea_wood"), STRIPPED_BRIGHT_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "stripped_azule_azalea_wood"), STRIPPED_AZULE_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_wood"), WALNUT_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_wood"), FISS_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_wood"), TITANIUM_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_wood"), TECAL_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_wood"), ROZE_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_wood"), BRIGHT_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_wood"), AZULE_AZALEA_WOOD_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_fence"), FISS_AZALEA_FENCE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_fence"), TITANIUM_AZALEA_FENCE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_fence"), WALNUT_AZALEA_FENCE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_fence"), ROZE_AZALEA_FENCE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_fence"), BRIGHT_AZALEA_FENCE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_fence"), TECAL_AZALEA_FENCE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_fence"), AZULE_AZALEA_FENCE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_fence_gate"), FISS_AZALEA_FENCE_GATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_fence_gate"), TITANIUM_AZALEA_FENCE_GATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_fence_gate"), WALNUT_AZALEA_FENCE_GATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_fence_gate"), ROZE_AZALEA_FENCE_GATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_fence_gate"), BRIGHT_AZALEA_FENCE_GATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_fence_gate"), TECAL_AZALEA_FENCE_GATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_fence_gate"), AZULE_AZALEA_FENCE_GATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_trapdoor"), FISS_AZALEA_TRAPDOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_trapdoor"), TITANIUM_AZALEA_TRAPDOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_trapdoor"), WALNUT_AZALEA_TRAPDOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_trapdoor"), ROZE_AZALEA_TRAPDOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_trapdoor"), BRIGHT_AZALEA_TRAPDOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_trapdoor"), TECAL_AZALEA_TRAPDOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_trapdoor"), AZULE_AZALEA_TRAPDOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_door"), FISS_AZALEA_DOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_door"), TITANIUM_AZALEA_DOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_door"), WALNUT_AZALEA_DOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_door"), ROZE_AZALEA_DOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_door"), BRIGHT_AZALEA_DOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_door"), TECAL_AZALEA_DOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_door"), AZULE_AZALEA_DOOR_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_stairs"), FISS_AZALEA_STAIRS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_stairs"), TITANIUM_AZALEA_STAIRS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_stairs"), WALNUT_AZALEA_STAIRS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_stairs"), ROZE_AZALEA_STAIRS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_stairs"), BRIGHT_AZALEA_STAIRS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_stairs"), TECAL_AZALEA_STAIRS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_stairs"), AZULE_AZALEA_STAIRS_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_slab"), FISS_AZALEA_SLAB_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_slab"), TITANIUM_AZALEA_SLAB_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_slab"), WALNUT_AZALEA_SLAB_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_slab"), ROZE_AZALEA_SLAB_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_slab"), BRIGHT_AZALEA_SLAB_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_slab"), TECAL_AZALEA_SLAB_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_slab"), AZULE_AZALEA_SLAB_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_button"), FISS_AZALEA_BUTTON_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_button"), TITANIUM_AZALEA_BUTTON_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_button"), WALNUT_AZALEA_BUTTON_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_button"), ROZE_AZALEA_BUTTON_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_button"), BRIGHT_AZALEA_BUTTON_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_button"), TECAL_AZALEA_BUTTON_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_button"), AZULE_AZALEA_BUTTON_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "fiss_azalea_pressure_plate"), FISS_AZALEA_PRESSURE_PLATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "titanium_azalea_pressure_plate"), TITANIUM_AZALEA_PRESSURE_PLATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "walnut_azalea_pressure_plate"), WALNUT_AZALEA_PRESSURE_PLATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "roze_azalea_pressure_plate"), ROZE_AZALEA_PRESSURE_PLATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "bright_azalea_pressure_plate"), BRIGHT_AZALEA_PRESSURE_PLATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "tecal_azalea_pressure_plate"), TECAL_AZALEA_PRESSURE_PLATE_ITEM);
        Registry.register(Registry.ITEM, new ResourceLocation(ColorfulAzaleas.MODID, "azule_azalea_pressure_plate"), AZULE_AZALEA_PRESSURE_PLATE_ITEM);
    }
}